[2025-02-20T00:00:06.170+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-20T00:00:06.177+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_climate.extract_data scheduled__2025-02-19T00:00:00+00:00 [queued]>
[2025-02-20T00:00:06.180+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_climate.extract_data scheduled__2025-02-19T00:00:00+00:00 [queued]>
[2025-02-20T00:00:06.181+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-20T00:00:06.191+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): extract_data> on 2025-02-19 00:00:00+00:00
[2025-02-20T00:00:06.197+0000] {standard_task_runner.py:72} INFO - Started process 4586 to run task
[2025-02-20T00:00:06.213+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_climate', 'extract_data', 'scheduled__2025-02-19T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/climate_extract_dag.py', '--cfg-path', '/tmp/tmpb5jkqy6u']
[2025-02-20T00:00:06.216+0000] {standard_task_runner.py:105} INFO - Job 39: Subtask extract_data
[2025-02-20T00:00:06.245+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_climate.extract_data scheduled__2025-02-19T00:00:00+00:00 [running]> on host f1d396ca8f61
[2025-02-20T00:00:06.284+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_climate' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-19T00:00:00+00:00'
[2025-02-20T00:00:06.284+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-20T00:00:06.366+0000] {docker.py:379} INFO - Starting docker container from image dbt_docker_image
[2025-02-20T00:00:06.399+0000] {docker.py:387} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-02-20T00:00:10.543+0000] {docker.py:73} INFO - [0m00:00:10  Running with dbt=1.9.2
[2025-02-20T00:00:10.916+0000] {docker.py:73} INFO - [0m00:00:10  Registered adapter: duckdb=1.9.1
[2025-02-20T00:00:10.972+0000] {docker.py:73} INFO - [0m00:00:10  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2025-02-20T00:00:12.108+0000] {docker.py:73} INFO - [0m00:00:12  Found 1 model, 1 seed, 19 data tests, 424 macros
[2025-02-20T00:00:12.109+0000] {docker.py:73} INFO - [0m00:00:12
[2025-02-20T00:00:12.109+0000] {docker.py:73} INFO - [0m00:00:12  Concurrency: 1 threads (target='dev')
[2025-02-20T00:00:12.110+0000] {docker.py:73} INFO - [0m00:00:12
[2025-02-20T00:00:15.249+0000] {docker.py:73} INFO - [0m00:00:15  1 of 1 START sql table model main.open_meteo_raw_data .......................... [RUN]
[2025-02-20T00:00:42.828+0000] {docker.py:73} INFO - [0m00:00:42  1 of 1 OK created sql table model main.open_meteo_raw_data ..................... [[32mOK[0m in 27.57s]
[2025-02-20T00:00:42.927+0000] {docker.py:73} INFO - [0m00:00:42
[2025-02-20T00:00:42.928+0000] {docker.py:73} INFO - [0m00:00:42  Finished running 1 table model in 0 hours 0 minutes and 30.81 seconds (30.81s).
[2025-02-20T00:00:43.076+0000] {docker.py:73} INFO - [0m00:00:43
[2025-02-20T00:00:43.077+0000] {docker.py:73} INFO - [0m00:00:43  [32mCompleted successfully[0m
[2025-02-20T00:00:43.077+0000] {docker.py:73} INFO - [0m00:00:43
[2025-02-20T00:00:43.078+0000] {docker.py:73} INFO - [0m00:00:43  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-20T00:00:43.820+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-20T00:00:43.821+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_climate, task_id=extract_data, run_id=scheduled__2025-02-19T00:00:00+00:00, execution_date=20250219T000000, start_date=20250220T000006, end_date=20250220T000043
[2025-02-20T00:00:43.863+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-20T00:00:43.876+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-20T00:00:43.877+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
