[2025-02-20T14:25:11.283+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-20T14:25:11.313+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_climate.extract_data manual__2025-02-20T14:25:07.834890+00:00 [queued]>
[2025-02-20T14:25:11.317+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_climate.extract_data manual__2025-02-20T14:25:07.834890+00:00 [queued]>
[2025-02-20T14:25:11.317+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-20T14:25:11.333+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): extract_data> on 2025-02-20 14:25:07.834890+00:00
[2025-02-20T14:25:11.339+0000] {standard_task_runner.py:72} INFO - Started process 5197 to run task
[2025-02-20T14:25:11.344+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_climate', 'extract_data', 'manual__2025-02-20T14:25:07.834890+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/climate_extract_dag.py', '--cfg-path', '/tmp/tmpo43z3zym']
[2025-02-20T14:25:11.348+0000] {standard_task_runner.py:105} INFO - Job 45: Subtask extract_data
[2025-02-20T14:25:11.386+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_climate.extract_data manual__2025-02-20T14:25:07.834890+00:00 [running]> on host f1d396ca8f61
[2025-02-20T14:25:11.440+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_climate' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-20T14:25:07.834890+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-20T14:25:07.834890+00:00'
[2025-02-20T14:25:11.441+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-20T14:25:11.490+0000] {docker.py:379} INFO - Starting docker container from image dbt_docker_image
[2025-02-20T14:25:11.512+0000] {docker.py:387} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-02-20T14:25:15.254+0000] {docker.py:73} INFO - [0m14:25:15  Running with dbt=1.9.2
[2025-02-20T14:25:15.531+0000] {docker.py:73} INFO - [0m14:25:15  Registered adapter: duckdb=1.9.1
[2025-02-20T14:25:15.595+0000] {docker.py:73} INFO - [0m14:25:15  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2025-02-20T14:25:16.719+0000] {docker.py:73} INFO - [0m14:25:16  Found 1 model, 1 seed, 19 data tests, 424 macros
[2025-02-20T14:25:16.722+0000] {docker.py:73} INFO - [0m14:25:16
[2025-02-20T14:25:16.725+0000] {docker.py:73} INFO - [0m14:25:16  Concurrency: 1 threads (target='dev')
[2025-02-20T14:25:16.726+0000] {docker.py:73} INFO - [0m14:25:16
[2025-02-20T14:25:18.439+0000] {docker.py:73} INFO - [0m14:25:18  1 of 1 START sql table model main.open_meteo_raw_data .......................... [RUN]
[2025-02-20T14:25:51.834+0000] {docker.py:73} INFO - [0m14:25:51  1 of 1 OK created sql table model main.open_meteo_raw_data ..................... [[32mOK[0m in 33.39s]
[2025-02-20T14:25:51.900+0000] {docker.py:73} INFO - [0m14:25:51
[2025-02-20T14:25:51.900+0000] {docker.py:73} INFO - [0m14:25:51  Finished running 1 table model in 0 hours 0 minutes and 35.18 seconds (35.18s).
[2025-02-20T14:25:52.005+0000] {docker.py:73} INFO - [0m14:25:52
[2025-02-20T14:25:52.006+0000] {docker.py:73} INFO - [0m14:25:52  [32mCompleted successfully[0m
[2025-02-20T14:25:52.006+0000] {docker.py:73} INFO - [0m14:25:52
[2025-02-20T14:25:52.007+0000] {docker.py:73} INFO - [0m14:25:52  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-20T14:25:52.720+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-20T14:25:52.721+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_climate, task_id=extract_data, run_id=manual__2025-02-20T14:25:07.834890+00:00, execution_date=20250220T142507, start_date=20250220T142511, end_date=20250220T142552
[2025-02-20T14:25:52.760+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-20T14:25:52.781+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-20T14:25:52.782+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
