[2025-02-18T00:00:04.579+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T00:00:04.585+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_climate.extract_data scheduled__2025-02-17T00:00:00+00:00 [queued]>
[2025-02-18T00:00:04.587+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_climate.extract_data scheduled__2025-02-17T00:00:00+00:00 [queued]>
[2025-02-18T00:00:04.588+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-18T00:00:04.596+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): extract_data> on 2025-02-17 00:00:00+00:00
[2025-02-18T00:00:04.599+0000] {standard_task_runner.py:72} INFO - Started process 3670 to run task
[2025-02-18T00:00:04.606+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_climate', 'extract_data', 'scheduled__2025-02-17T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/climate_extract_dag.py', '--cfg-path', '/tmp/tmpeavfcv00']
[2025-02-18T00:00:04.613+0000] {standard_task_runner.py:105} INFO - Job 28: Subtask extract_data
[2025-02-18T00:00:04.713+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_climate.extract_data scheduled__2025-02-17T00:00:00+00:00 [running]> on host c51dc0d039e5
[2025-02-18T00:00:04.788+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_climate' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-17T00:00:00+00:00'
[2025-02-18T00:00:04.790+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-18T00:00:04.840+0000] {docker.py:379} INFO - Starting docker container from image dbt_docker_image
[2025-02-18T00:00:04.869+0000] {docker.py:387} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-02-18T00:00:08.108+0000] {docker.py:73} INFO - [0m00:00:08  Running with dbt=1.9.2
[2025-02-18T00:00:08.356+0000] {docker.py:73} INFO - [0m00:00:08  Registered adapter: duckdb=1.9.1
[2025-02-18T00:00:08.411+0000] {docker.py:73} INFO - [0m00:00:08  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2025-02-18T00:00:09.499+0000] {docker.py:73} INFO - [0m00:00:09  Found 1 model, 1 seed, 19 data tests, 424 macros
[2025-02-18T00:00:09.500+0000] {docker.py:73} INFO - [0m00:00:09
[2025-02-18T00:00:09.500+0000] {docker.py:73} INFO - [0m00:00:09  Concurrency: 1 threads (target='dev')
[2025-02-18T00:00:09.500+0000] {docker.py:73} INFO - [0m00:00:09
[2025-02-18T00:00:11.748+0000] {docker.py:73} INFO - [0m00:00:11  1 of 1 START sql table model main.open_meteo_raw_data .......................... [RUN]
[2025-02-18T00:00:38.670+0000] {docker.py:73} INFO - [0m00:00:38  1 of 1 OK created sql table model main.open_meteo_raw_data ..................... [[32mOK[0m in 26.92s]
[2025-02-18T00:00:38.707+0000] {docker.py:73} INFO - [0m00:00:38
[2025-02-18T00:00:38.707+0000] {docker.py:73} INFO - [0m00:00:38  Finished running 1 table model in 0 hours 0 minutes and 29.20 seconds (29.20s).
[2025-02-18T00:00:38.764+0000] {docker.py:73} INFO - [0m00:00:38
[2025-02-18T00:00:38.764+0000] {docker.py:73} INFO - [0m00:00:38  [32mCompleted successfully[0m
[2025-02-18T00:00:38.765+0000] {docker.py:73} INFO - [0m00:00:38
[2025-02-18T00:00:38.765+0000] {docker.py:73} INFO - [0m00:00:38  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-18T00:00:39.266+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-18T00:00:39.267+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_climate, task_id=extract_data, run_id=scheduled__2025-02-17T00:00:00+00:00, execution_date=20250217T000000, start_date=20250218T000004, end_date=20250218T000039
[2025-02-18T00:00:39.287+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T00:00:39.294+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-18T00:00:39.294+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
