[2025-02-17T00:00:03.758+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-17T00:00:03.763+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_climate.extract_data scheduled__2025-02-16T00:00:00+00:00 [queued]>
[2025-02-17T00:00:03.766+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_climate.extract_data scheduled__2025-02-16T00:00:00+00:00 [queued]>
[2025-02-17T00:00:03.766+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-17T00:00:03.774+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): extract_data> on 2025-02-16 00:00:00+00:00
[2025-02-17T00:00:03.777+0000] {standard_task_runner.py:72} INFO - Started process 789 to run task
[2025-02-17T00:00:03.780+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_climate', 'extract_data', 'scheduled__2025-02-16T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/climate_extract_dag.py', '--cfg-path', '/tmp/tmpgojewo31']
[2025-02-17T00:00:03.782+0000] {standard_task_runner.py:105} INFO - Job 27: Subtask extract_data
[2025-02-17T00:00:03.814+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_climate.extract_data scheduled__2025-02-16T00:00:00+00:00 [running]> on host c51dc0d039e5
[2025-02-17T00:00:03.852+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_climate' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-16T00:00:00+00:00'
[2025-02-17T00:00:03.853+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-17T00:00:03.894+0000] {docker.py:379} INFO - Starting docker container from image dbt_docker_image
[2025-02-17T00:00:03.916+0000] {docker.py:387} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-02-17T00:00:06.165+0000] {docker.py:73} INFO - [0m00:00:06  Running with dbt=1.9.2
[2025-02-17T00:00:06.382+0000] {docker.py:73} INFO - [0m00:00:06  Registered adapter: duckdb=1.9.1
[2025-02-17T00:00:06.431+0000] {docker.py:73} INFO - [0m00:00:06  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2025-02-17T00:00:07.512+0000] {docker.py:73} INFO - [0m00:00:07  Found 1 model, 1 seed, 19 data tests, 424 macros
[2025-02-17T00:00:07.513+0000] {docker.py:73} INFO - [0m00:00:07
[2025-02-17T00:00:07.513+0000] {docker.py:73} INFO - [0m00:00:07  Concurrency: 1 threads (target='dev')
[2025-02-17T00:00:07.514+0000] {docker.py:73} INFO - [0m00:00:07
[2025-02-17T00:00:09.484+0000] {docker.py:73} INFO - [0m00:00:09  1 of 1 START sql table model main.open_meteo_raw_data .......................... [RUN]
[2025-02-17T00:00:36.620+0000] {docker.py:73} INFO - [0m00:00:36  1 of 1 OK created sql table model main.open_meteo_raw_data ..................... [[32mOK[0m in 27.13s]
[2025-02-17T00:00:36.657+0000] {docker.py:73} INFO - [0m00:00:36
[2025-02-17T00:00:36.657+0000] {docker.py:73} INFO - [0m00:00:36  Finished running 1 table model in 0 hours 0 minutes and 29.14 seconds (29.14s).
[2025-02-17T00:00:36.721+0000] {docker.py:73} INFO - [0m00:00:36
[2025-02-17T00:00:36.722+0000] {docker.py:73} INFO - [0m00:00:36  [32mCompleted successfully[0m
[2025-02-17T00:00:36.722+0000] {docker.py:73} INFO - [0m00:00:36
[2025-02-17T00:00:36.722+0000] {docker.py:73} INFO - [0m00:00:36  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-17T00:00:37.272+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-17T00:00:37.273+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_climate, task_id=extract_data, run_id=scheduled__2025-02-16T00:00:00+00:00, execution_date=20250216T000000, start_date=20250217T000003, end_date=20250217T000037
[2025-02-17T00:00:37.288+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-17T00:00:37.296+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-17T00:00:37.297+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
