[2025-02-15T01:31:21.433+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-15T01:31:21.438+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_climate.extract_data manual__2025-02-15T01:30:48.492612+00:00 [queued]>
[2025-02-15T01:31:21.441+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_climate.extract_data manual__2025-02-15T01:30:48.492612+00:00 [queued]>
[2025-02-15T01:31:21.442+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-15T01:31:21.450+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): extract_data> on 2025-02-15 01:30:48.492612+00:00
[2025-02-15T01:31:21.453+0000] {standard_task_runner.py:72} INFO - Started process 243 to run task
[2025-02-15T01:31:21.455+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_climate', 'extract_data', 'manual__2025-02-15T01:30:48.492612+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/climate_extract_dag.py', '--cfg-path', '/tmp/tmpxg2oxr3o']
[2025-02-15T01:31:21.456+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask extract_data
[2025-02-15T01:31:21.479+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_climate.extract_data manual__2025-02-15T01:30:48.492612+00:00 [running]> on host 4360a910c8ec
[2025-02-15T01:31:21.512+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_climate' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-15T01:30:48.492612+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-15T01:30:48.492612+00:00'
[2025-02-15T01:31:21.513+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-15T01:31:21.541+0000] {docker.py:379} INFO - Starting docker container from image dbt_docker
[2025-02-15T01:31:21.555+0000] {docker.py:387} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-02-15T01:31:23.674+0000] {docker.py:73} INFO - [0m01:31:23  Running with dbt=1.9.2
[2025-02-15T01:31:23.876+0000] {docker.py:73} INFO - [0m01:31:23  Registered adapter: duckdb=1.9.1
[2025-02-15T01:31:23.928+0000] {docker.py:73} INFO - [0m01:31:23  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2025-02-15T01:31:25.044+0000] {docker.py:73} INFO - [0m01:31:25  Found 2 models, 1 seed, 28 data tests, 424 macros
[2025-02-15T01:31:25.045+0000] {docker.py:73} INFO - [0m01:31:25
[2025-02-15T01:31:25.046+0000] {docker.py:73} INFO - [0m01:31:25  Concurrency: 1 threads (target='dev')
[2025-02-15T01:31:25.046+0000] {docker.py:73} INFO - [0m01:31:25
[2025-02-15T01:31:26.553+0000] {docker.py:73} INFO - [0m01:31:26  1 of 1 START sql table model main.open_meteo_raw_data .......................... [RUN]
[2025-02-15T01:31:52.805+0000] {docker.py:73} INFO - [0m01:31:52  1 of 1 OK created sql table model main.open_meteo_raw_data ..................... [[32mOK[0m in 26.25s]
[2025-02-15T01:31:52.858+0000] {docker.py:73} INFO - [0m01:31:52
[2025-02-15T01:31:52.858+0000] {docker.py:73} INFO - [0m01:31:52  Finished running 1 table model in 0 hours 0 minutes and 27.81 seconds (27.81s).
[2025-02-15T01:31:52.950+0000] {docker.py:73} INFO - [0m01:31:52
[2025-02-15T01:31:52.951+0000] {docker.py:73} INFO - [0m01:31:52  [32mCompleted successfully[0m
[2025-02-15T01:31:52.951+0000] {docker.py:73} INFO - [0m01:31:52
[2025-02-15T01:31:52.952+0000] {docker.py:73} INFO - [0m01:31:52  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-15T01:31:53.493+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-15T01:31:53.494+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_climate, task_id=extract_data, run_id=manual__2025-02-15T01:30:48.492612+00:00, execution_date=20250215T013048, start_date=20250215T013121, end_date=20250215T013153
[2025-02-15T01:31:53.524+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-15T01:31:53.536+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-15T01:31:53.537+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
