[2025-02-20T14:01:21.904+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-20T14:01:21.910+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_climate.extract_data manual__2025-02-20T14:01:16.274663+00:00 [queued]>
[2025-02-20T14:01:21.913+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_climate.extract_data manual__2025-02-20T14:01:16.274663+00:00 [queued]>
[2025-02-20T14:01:21.913+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-20T14:01:21.922+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): extract_data> on 2025-02-20 14:01:16.274663+00:00
[2025-02-20T14:01:21.932+0000] {standard_task_runner.py:72} INFO - Started process 4922 to run task
[2025-02-20T14:01:21.937+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_climate', 'extract_data', 'manual__2025-02-20T14:01:16.274663+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/climate_extract_dag.py', '--cfg-path', '/tmp/tmpump40oi7']
[2025-02-20T14:01:21.946+0000] {standard_task_runner.py:105} INFO - Job 41: Subtask extract_data
[2025-02-20T14:01:22.020+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_climate.extract_data manual__2025-02-20T14:01:16.274663+00:00 [running]> on host f1d396ca8f61
[2025-02-20T14:01:22.104+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_climate' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-20T14:01:16.274663+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-20T14:01:16.274663+00:00'
[2025-02-20T14:01:22.105+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-20T14:01:22.195+0000] {docker.py:379} INFO - Starting docker container from image dbt_docker_image
[2025-02-20T14:01:22.230+0000] {docker.py:387} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-02-20T14:01:26.262+0000] {docker.py:73} INFO - [0m14:01:26  Running with dbt=1.9.2
[2025-02-20T14:01:26.606+0000] {docker.py:73} INFO - [0m14:01:26  Registered adapter: duckdb=1.9.1
[2025-02-20T14:01:26.664+0000] {docker.py:73} INFO - [0m14:01:26  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2025-02-20T14:01:27.887+0000] {docker.py:73} INFO - [0m14:01:27  Found 1 model, 1 seed, 19 data tests, 424 macros
[2025-02-20T14:01:27.890+0000] {docker.py:73} INFO - [0m14:01:27
[2025-02-20T14:01:27.891+0000] {docker.py:73} INFO - [0m14:01:27  Concurrency: 1 threads (target='dev')
[2025-02-20T14:01:27.891+0000] {docker.py:73} INFO - [0m14:01:27
[2025-02-20T14:01:30.699+0000] {docker.py:73} INFO - [0m14:01:30  1 of 1 START sql table model main.open_meteo_raw_data .......................... [RUN]
[2025-02-20T14:02:03.550+0000] {docker.py:73} INFO - [0m14:02:03  1 of 1 OK created sql table model main.open_meteo_raw_data ..................... [[32mOK[0m in 32.83s]
[2025-02-20T14:02:03.621+0000] {docker.py:73} INFO - [0m14:02:03
[2025-02-20T14:02:03.622+0000] {docker.py:73} INFO - [0m14:02:03  Finished running 1 table model in 0 hours 0 minutes and 35.73 seconds (35.73s).
[2025-02-20T14:02:03.717+0000] {docker.py:73} INFO - [0m14:02:03
[2025-02-20T14:02:03.718+0000] {docker.py:73} INFO - [0m14:02:03  [32mCompleted successfully[0m
[2025-02-20T14:02:03.718+0000] {docker.py:73} INFO - [0m14:02:03
[2025-02-20T14:02:03.718+0000] {docker.py:73} INFO - [0m14:02:03  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-20T14:02:04.438+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-20T14:02:04.438+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_climate, task_id=extract_data, run_id=manual__2025-02-20T14:01:16.274663+00:00, execution_date=20250220T140116, start_date=20250220T140121, end_date=20250220T140204
[2025-02-20T14:02:04.467+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-20T14:02:04.476+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-20T14:02:04.477+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
