[2025-02-16T15:30:49.079+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-16T15:30:49.084+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_climate.extract_data manual__2025-02-16T15:30:46.665836+00:00 [queued]>
[2025-02-16T15:30:49.087+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_climate.extract_data manual__2025-02-16T15:30:46.665836+00:00 [queued]>
[2025-02-16T15:30:49.087+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-16T15:30:49.095+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): extract_data> on 2025-02-16 15:30:46.665836+00:00
[2025-02-16T15:30:49.098+0000] {standard_task_runner.py:72} INFO - Started process 507 to run task
[2025-02-16T15:30:49.101+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_climate', 'extract_data', 'manual__2025-02-16T15:30:46.665836+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/climate_extract_dag.py', '--cfg-path', '/tmp/tmppfqk91om']
[2025-02-16T15:30:49.103+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask extract_data
[2025-02-16T15:30:49.131+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_climate.extract_data manual__2025-02-16T15:30:46.665836+00:00 [running]> on host 4360a910c8ec
[2025-02-16T15:30:49.171+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_climate' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-16T15:30:46.665836+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-16T15:30:46.665836+00:00'
[2025-02-16T15:30:49.171+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-16T15:30:49.202+0000] {docker.py:379} INFO - Starting docker container from image dbt_docker
[2025-02-16T15:30:49.216+0000] {docker.py:387} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-02-16T15:30:51.466+0000] {docker.py:73} INFO - [0m15:30:51  Running with dbt=1.9.2
[2025-02-16T15:30:51.657+0000] {docker.py:73} INFO - [0m15:30:51  Registered adapter: duckdb=1.9.1
[2025-02-16T15:30:51.706+0000] {docker.py:73} INFO - [0m15:30:51  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2025-02-16T15:30:52.753+0000] {docker.py:73} INFO - [0m15:30:52  Found 2 models, 1 seed, 28 data tests, 424 macros
[2025-02-16T15:30:52.754+0000] {docker.py:73} INFO - [0m15:30:52
[2025-02-16T15:30:52.755+0000] {docker.py:73} INFO - [0m15:30:52  Concurrency: 1 threads (target='dev')
[2025-02-16T15:30:52.755+0000] {docker.py:73} INFO - [0m15:30:52
[2025-02-16T15:30:54.763+0000] {docker.py:73} INFO - [0m15:30:54  1 of 1 START sql table model main.open_meteo_raw_data .......................... [RUN]
[2025-02-16T15:31:22.076+0000] {docker.py:73} INFO - [0m15:31:22  1 of 1 OK created sql table model main.open_meteo_raw_data ..................... [[32mOK[0m in 27.31s]
[2025-02-16T15:31:22.113+0000] {docker.py:73} INFO - [0m15:31:22
[2025-02-16T15:31:22.113+0000] {docker.py:73} INFO - [0m15:31:22  Finished running 1 table model in 0 hours 0 minutes and 29.36 seconds (29.36s).
[2025-02-16T15:31:22.171+0000] {docker.py:73} INFO - [0m15:31:22
[2025-02-16T15:31:22.172+0000] {docker.py:73} INFO - [0m15:31:22  [32mCompleted successfully[0m
[2025-02-16T15:31:22.172+0000] {docker.py:73} INFO - [0m15:31:22
[2025-02-16T15:31:22.173+0000] {docker.py:73} INFO - [0m15:31:22  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-16T15:31:22.587+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-16T15:31:22.587+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_climate, task_id=extract_data, run_id=manual__2025-02-16T15:30:46.665836+00:00, execution_date=20250216T153046, start_date=20250216T153049, end_date=20250216T153122
[2025-02-16T15:31:22.617+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-16T15:31:22.623+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-16T15:31:22.623+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
