[2025-02-15T01:23:28.122+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-15T01:23:28.128+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_climate.extract_data manual__2025-02-15T01:22:47.305488+00:00 [queued]>
[2025-02-15T01:23:28.130+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_climate.extract_data manual__2025-02-15T01:22:47.305488+00:00 [queued]>
[2025-02-15T01:23:28.130+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-15T01:23:28.138+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): extract_data> on 2025-02-15 01:22:47.305488+00:00
[2025-02-15T01:23:28.140+0000] {standard_task_runner.py:72} INFO - Started process 120 to run task
[2025-02-15T01:23:28.142+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_climate', 'extract_data', 'manual__2025-02-15T01:22:47.305488+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/climate_extract_dag.py', '--cfg-path', '/tmp/tmpjv52c072']
[2025-02-15T01:23:28.143+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask extract_data
[2025-02-15T01:23:28.162+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_climate.extract_data manual__2025-02-15T01:22:47.305488+00:00 [running]> on host 4360a910c8ec
[2025-02-15T01:23:28.191+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_climate' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-15T01:22:47.305488+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-15T01:22:47.305488+00:00'
[2025-02-15T01:23:28.192+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-15T01:23:28.216+0000] {docker.py:379} INFO - Starting docker container from image dbt_docker
[2025-02-15T01:23:28.222+0000] {docker.py:387} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-02-15T01:23:30.266+0000] {docker.py:73} INFO - [0m01:23:30  Running with dbt=1.9.2
[2025-02-15T01:23:30.486+0000] {docker.py:73} INFO - [0m01:23:30  Registered adapter: duckdb=1.9.1
[2025-02-15T01:23:30.537+0000] {docker.py:73} INFO - [0m01:23:30  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2025-02-15T01:23:31.622+0000] {docker.py:73} INFO - [0m01:23:31  Found 2 models, 1 seed, 28 data tests, 424 macros
[2025-02-15T01:23:31.623+0000] {docker.py:73} INFO - [0m01:23:31
[2025-02-15T01:23:31.623+0000] {docker.py:73} INFO - [0m01:23:31  Concurrency: 1 threads (target='dev')
[2025-02-15T01:23:31.624+0000] {docker.py:73} INFO - [0m01:23:31
[2025-02-15T01:23:33.131+0000] {docker.py:73} INFO - [0m01:23:33  1 of 1 START sql table model main.open_meteo_raw_data .......................... [RUN]
[2025-02-15T01:23:59.640+0000] {docker.py:73} INFO - [0m01:23:59  1 of 1 OK created sql table model main.open_meteo_raw_data ..................... [[32mOK[0m in 26.50s]
[2025-02-15T01:23:59.685+0000] {docker.py:73} INFO - [0m01:23:59
[2025-02-15T01:23:59.685+0000] {docker.py:73} INFO - [0m01:23:59  Finished running 1 table model in 0 hours 0 minutes and 28.06 seconds (28.06s).
[2025-02-15T01:23:59.772+0000] {docker.py:73} INFO - [0m01:23:59
[2025-02-15T01:23:59.772+0000] {docker.py:73} INFO - [0m01:23:59  [32mCompleted successfully[0m
[2025-02-15T01:23:59.772+0000] {docker.py:73} INFO - [0m01:23:59
[2025-02-15T01:23:59.773+0000] {docker.py:73} INFO - [0m01:23:59  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-15T01:24:00.326+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-15T01:24:00.326+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_climate, task_id=extract_data, run_id=manual__2025-02-15T01:22:47.305488+00:00, execution_date=20250215T012247, start_date=20250215T012328, end_date=20250215T012400
[2025-02-15T01:24:00.348+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-15T01:24:00.356+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-15T01:24:00.356+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
